# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'Swift4Test' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!


    pod 'RxSwift', '~> 5.0'
    pod 'RxCocoa', '~> 5.0'
    pod 'Segmentio', '~> 3.3'
    pod 'SideMenuSwift'
end
